[package]
name = "fastn-runtime"
version = "0.1.0"
edition = "2021"

[features]
default = ["native"]
native = ["winit", "env_logger", "log", "wgpu"]
# terminal = ["crossterm"]
# web = ["wasm-bindgen", "web-sys"]

[dependencies]
winit = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
log = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
taffy.workspace = true
serde.workspace = true
slotmap.workspace = true
once_cell.workspace = true
thiserror.workspace = true
tokio.workspace = true
bytemuck.workspace = true
wasmtime.workspace = true
bitflags.workspace = true
async-trait.workspace = true
pretty.workspace = true
fastn-wasm = { path = "../fastn-wasm" }
