[workspace]
members = [
    "ftd",
    "fastn",
    "fastn-core",
    "fastn-cloud",
    "fastn-package",
]

[workspace.dependencies]
actix-web = "4"
antidote = "1"
async-lock = "2"
async-recursion = "1"
async-trait = "0.1"
camino = "1"
clap = "4"
colored = "2"
diffy = "0.3"
edit = "0.1"
env_logger = "0.10"
fluent = "0.16"
ftd = { path = "../ftd" }
futures = "0.3"
home = "0.5"
ignore = "0.4"
indoc = "2"
intl-memoizer = "0.5"
itertools = "0.10"
mime_guess = "2"
oauth2 = { version = "4" }
once_cell = "1"
realm-lang = "0.1"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
rusqlite = "0.29.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
slug = { version = "0.1" }
tejar = "0.1"
thiserror = "1"
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
walkdir = "2"
zip = "0.6"

[workspace.dependencies.tracing-forest]
version = "0.1"
features = [
    "ansi", # This is for printing the ColorLevel in the events
    "smallvec",
    "serde",
    "tokio",

    # "uuid",  # This is for printing uuid for every request
    # "chrono", # This is for printing the time of the event
    # "env-filter",
]