[package]
name = "ftd"
version = "0.1.2"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "mxfunc <deepak@fifthtry.com>",
    "Abrar Khan <abrar.nitk@gmail.com>"
]
description = "FifthTry Document Language"
license-file = "LICENSE"
include = ["src/**/*", "Cargo.toml"]
readme = "README.md"
keywords = ["fifthtry"]
edition = "2018"
repository = "https://github.com/fifthtry/ftd"

[dependencies]
Inflector = "0.11.4"
comrak = "0.7.0"
lazy_static = "1"
linked-hash-map = { version = "0.5.4", features = ["serde_impl"]}
percent-encoding = "2.1.0"
serde = "1"
serde_derive = "1"
syntect = "4"
thiserror = "1"
unindent = "0.1.3"
css-color-parser = "0.1.2"
slug = "0.1.4"
katex = "0.3"
realm-lang = "0.1.0"
observer = "0.2.5"

[dev-dependencies]
diffy = "0.2.0"
indoc = "0.3"
pretty_assertions = "0.6"
