[package]
name = "ftd"
version = "0.1.18"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Sourabh Garg <sourabh@fifthtry.com>"
]
edition = "2018"
description = "ftd: FifthTry Document Format"
license = "MIT"
repository = "https://github.com/FifthTry/ftd"
homepage = "https://ftd.dev"

[dependencies]
css-color-parser = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
comrak = "0.14"
syntect = { version = "5", default-features = false, features = ["default-fancy"] }
lazy_static = "1"
regex = "1"
format_num = "0.1"
failure = "0.1"
slug = "0.1"
include_dir = "0.7"
indoc = "1"
itertools = "0.10"

[dev-dependencies]
diffy = "0.2"
pretty_assertions = "1.2"
