[package]
name = "ftd"
version = "0.1.18"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Sourabh Garg <sourabh@fifthtry.com>"
]
edition = "2018"
description = "ftd: FifthTry Document Format"
license = "MIT"
repository = "https://github.com/FifthTry/ftd"
homepage = "https://ftd.dev"

[dependencies]
css-color-parser = { version = "0.1.2" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = "1"
comrak = { version = "0.7.0" }
syntect = { version = "4.5.0", default-features = false, features = ["default-fancy"] }
lazy_static = { version = "1" }
regex = { version = "1.5.4" }
format_num = { version = "0.1.0" }
failure = "0.1"
slug = { version = "0.1.4" }
include_dir = "0.7.2"
indoc = "1.0"
itertools = "0.10.3"

[dev-dependencies]
diffy = "0.2.0"
pretty_assertions = "0.6"
