[package]
name = "fastn-js"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
quick-js.workspace = true
pretty.workspace = true
ftd.workspace = true
itertools.workspace = true

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
