[package]
name = "test"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 's'

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = {  version = "1", features = ["derive"] }
serde_json = "1"
http = "1"
bytes = "1"
diesel = { version = ">=2, <2.2", default-features = false, features = ["chrono"] }
thiserror = "1"
chrono = { version = "0.4", default-features = false, features = ["serde"] }


[dependencies.ft-sdk]
version = "0.1"
features = ["sqlite-default", "auth-provider", "field-extractors"]

