[package]
name = "fastn-package"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
camino = "1"
fastn-issues = { path = "../fastn-issues" }
ftd = { path = "../ftd" }
futures = "0.3"
rusqlite = "0.29.0"
serde = "1"
tokio = "1.27.0"
