[package]
name = "fastn-package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite.workspace = true
async-trait.workspace = true
thiserror.workspace = true
once_cell.workspace = true
tokio.workspace = true
camino.workspace = true
serde.workspace = true
ftd = { path = "../ftd" }
