[package]
name = "fastn-package"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite.workspace = true
async-trait.workspace = true
tokio.workspace = true
camino.workspace = true
serde.workspace = true
futures.workspace = true
ftd = { path = "../ftd" }
fastn-issues = { path = "../fastn-issues" }
