[package]
name = "fastn-p1"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

