[package]
name = "fastn"
version = "0.4.57"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
fastn-observer.workspace = true
fastn-update.workspace = true
fastn-core.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
fastn-ds.workspace = true
camino.workspace = true
