[package]
name = "fastn"
version = "0.2.0"
authors = [
    "Abrar Khan <abrark@fifthtry.com>",
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
]
edition = "2021"
description = "fastn: FTD Package Manager"
license = "MIT"
repository = "https://github.com/ftd-lang/fastn"
homepage = "https://fastn.io"

[dependencies]
tracing-forest = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
colored = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
clap = { workspace = true }
fastn-cloud = { path = "../fastn-cloud" }
fastn-core = { path = "../fastn-core" }
