[package]
name = "fastn"
version = "0.3.46"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
fastn-cloud.workspace = true
fastn-observer.workspace = true
fastn-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
