[package]
name = "fastn"
version = "0.4.44"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
colored.workspace = true
diesel = { workspace = true, optional = true }
diesel_migrations = { workspace = true, optional = true }
fastn-observer.workspace = true
fastn-update.workspace = true
fastn-core.workspace = true
futures.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
fastn-ds.workspace = true


[features]
auth = ["fastn-core/auth", "diesel", "diesel_migrations"]
