[package]
name = "fastn"
version = "0.2.0"
authors = [
    "Abrar Khan <abrark@fifthtry.com>",
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
]
edition = "2021"
description = "fastn: FTD Package Manager"
license = "MIT"
repository = "https://github.com/ftd-lang/fastn"
homepage = "https://fastn.io"

[dependencies]
clap.workspace = true
colored.workspace = true
fastn-cloud.workspace = true
fastn-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-forest.workspace = true
tracing-subscriber.workspace = true
