[package]
name = "fastn-wasm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
async-lock.workspace = true
actix-web.workspace = true
deadpool.workspace = true
deadpool-postgres.workspace = true
wasmtime.workspace = true
serde_json.workspace = true
serde.workspace = true
ft-sys-shared.workspace = true
rand.workspace = true
http.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
chrono.workspace = true
magic-crypt.workspace = true
scc.workspace = true
