[package]
name = "fastn"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
fastn-lang.workspace = true
fastn-static.workspace = true
fastn-core.workspace = true
serde.workspace = true
serde_json.workspace = true