[package]
name = "fastn-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc.workspace = true
wasmtime.workspace = true
itertools.workspace = true

[dev-dependencies]
wasmfmt.workspace = true
