[package]
name = "fastn-type"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
fastn-grammar.workspace = true
indexmap.workspace = true
fastn-js.workspace = true
itertools.workspace = true