[package]
name = "ftd"
version = "0.1.4"
authors = ["Amit Upadhyay <upadhyay@gmail.com>"]
edition = "2018"
description = "ftd: FifthTry Document Format parser"
license = "MIT"
repository = "https://github.com/fifthtry/ftd"
homepage = "https://www.fifthtry.com/fifthtry/ftd/"

[features]
default = []
fifthtry = [
    "comrak",
    "lazy_static",
    "linked-hash-map",
    "percent-encoding",
    "serde",
    "serde_derive",
    "syntect",
    "css-color-parser",
    "slug",
    "katex",
    "realm-lang",
    "observer",
    "rst_renderer",
    "rst_parser",
]

[dependencies]
thiserror = "1"

realm-lang = { path = "../realm/realm-lang", optional = true, version = "0.1.0" }
observer = { path = "../observer/observer", optional = true, version = "0.2.4" }

comrak = { version = "0.7.0", optional = true }
lazy_static = { version = "1", optional = true }
linked-hash-map = { version = "0.5.4", features = ["serde_impl"], optional = true}
percent-encoding = { version = "2.1.0", optional = true }
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }
syntect = { version = "4", optional = true }
css-color-parser = { version = "0.1.2", optional = true }
slug = { version = "0.1.4", optional = true }
katex = { version = "0.3", optional = true }
rst_renderer = {  version = '0.4', optional = true }
rst_parser = { version = '0.4', optional = true }

[dev-dependencies]
diffy = "0.2.0"
indoc = "0.3"
pretty_assertions = "0.6"
