[package]
name = "ftd"
version = "0.1.5"
authors = ["Amit Upadhyay <upadhyay@gmail.com>"]
edition = "2018"
description = "ftd: FifthTry Document Format parser"
license = "MIT"
repository = "https://github.com/fifthtry/ftd"
homepage = "https://www.fifthtry.com/fifthtry/ftd/"

[dependencies]
css-color-parser = { version = "0.1.2" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = "1"
comrak = { version = "0.7.0" }
katex = { version = "0.3" }
syntect = { version = "4.5.0", default-features = false, features = ["default-fancy"] }
lazy_static = { version = "1" }
regex = { version = "1.5.4" }
format_num = { version = "0.1.0" }
ftd-rt = { path = "../ftd-rt", version = "0.1.0" }


[dev-dependencies]
diffy = "0.2.0"
indoc = "0.3"
pretty_assertions = "0.6"
