[package]
name = "ftd"
version = "0.2.0"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Sourabh Garg <sourabh@fifthtry.com>"
]
edition = "2021"
description = "ftd: FifthTry Document Format"
license = "MIT"
repository = "https://github.com/FifthTry/ftd"
homepage = "https://fastn.io/ftd/"

[dependencies]
# Please do not specify a dependency more precisely than needed. If version "1" works, do
# not specify "1.1.42". This reduces the number of total dependencies, as if you specify
# 1.1.42 and someone else who only needed "1" also specified 1.1.37, we end up having same
# dependency compined twice.
#
# In future we may discover that our code does not indeed work with "1", say it ony works
# for 1.1 onwards, or 1.1.25 onwards, in which case use >= 1.1.25 etc. Saying our code
# only works for 1.1.42 and not 1.1.41 nor 1.1.43 is really weird, and most likely wrong.
#
# If you are not using the latest version intentionally, please do not list it in this section
# and create it's own [dependencies.<name>] section, and document it with why are you not
# using the latest dependency, and what is the plan.

css-color-parser.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
once_cell.workspace = true
regex.workspace = true
format_num.workspace = true
slug.workspace = true
include_dir.workspace = true
indoc.workspace = true
itertools.workspace = true
tracing.workspace = true
syntect.workspace = true
comrak.workspace = true



[dev-dependencies]
diffy.workspace = true
pretty_assertions.workspace = true
ron.workspace = true
rand.workspace = true
rand_pcg.workspace = true
rusty-hook.workspace = true

