[package]
name = "ftd"
version = "0.2.0"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Sourabh Garg <sourabh@fifthtry.com>"
]
edition = "2021"
description = "ftd: FifthTry Document Format"
license = "MIT"
repository = "https://github.com/FifthTry/ftd"
homepage = "https://fastn.io/ftd/"

[features]
default = []
terminal = ["rink", "dioxus-native-core", "dioxus-native-core-macro", "dioxus-html", "futures", "tokio", "rustc-hash"]

[dependencies]
comrak = "0.18"
css-color-parser = "0.1"
dioxus-html = { git = "https://github.com/DioxusLabs/dioxus", rev ="1adccc057357fa11c21327d18298f442bc6528e4", optional = true }
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev ="1adccc057357fa11c21327d18298f442bc6528e4", optional = true }
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev = "1adccc057357fa11c21327d18298f442bc6528e4", optional = true }
format_num = "0.1"
futures = { version = "0.3", optional = true }
include_dir = "0.7"
indoc = "2"
itertools = "0.10"
regex = "1"
rink = { git = "https://github.com/DioxusLabs/dioxus", rev = "1adccc057357fa11c21327d18298f442bc6528e4", optional = true }
rustc-hash = { version = "1", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slug = "0.1"
syntect = "5"
thiserror = "1"
tokio = { version = "1.27.0", features = ["full"], optional = true }
tracing = "0.1"

[dev-dependencies]
diffy = "0.3"
pretty_assertions = "1"
ron = "0.8"
rand = "0.8"
rand_pcg = "0.3"
rusty-hook = "^0.11.2"
