[workspace]
members = [
    "fastn",
    "fastn-compiler",
    "fastn-continuation",
    "fastn-package",
    "fastn-router",
    "fastn-section",
    "fastn-static",
    "fastn-unresolved",
    "fastn-update",
    "fastn-wasm",
]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
]
edition = "2021"
description = "fastn: Full-stack Web Development Made Easy"
license = "AGPL-3"
repository = "https://github.com/fastn-stack/fastn"
homepage = "https://fastn.com"


[workspace.dependencies]
# Please do not specify a dependency more precisely than needed. If version "1" works, do
# not specify "1.1.42". This reduces the number of total dependencies. For example, if you
# specify 1.1.42 and someone else who only needed "1" also specified 1.1.37, we end up having
# the same dependency getting compiled twice.
#
# In the future, we may discover that our code does not indeed work with "1", say it ony works
# for 1.1 onwards, or 1.1.25 onwards, in which case use >= 1.1.25 etc. Saying our code
# only works for 1.1.42 and not 1.1.41 nor 1.1.43 is really weird, and most likely wrong.
#
# If you are not using the latest version intentionally, please do not list it in this section
# and create its own [dependencies.<name>] section. Also, document it with why are you not
# using the latest dependency, and what is the plan to move to the latest version.

arcstr = "1"
async-trait = "0.1"
fastn-builtins = { path = "../fastn-builtins" }
fastn-compiler = { path = "fastn-compiler" }
fastn-continuation = { path = "fastn-continuation" }
fastn-package = { path = "fastn-package" }
fastn-resolved = { path = "../fastn-resolved" }
fastn-router = { path = "fastn-router" }
fastn-runtime = { path = "../fastn-runtime" }
fastn-section = { path = "fastn-section" }
fastn-unresolved = { path = "fastn-unresolved" }
ft-sys-shared = "0.1.4"
http = "1"
http-body-util = "0.1"
hyper = { version = "1.5.1", features = ["server", "http1"] }
hyper-util = { version = "0.1.10", features = ["tokio"] }
id-arena = "2"
indexmap = "2"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
string-interner = "0.18"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
wasmtime = "28"
chrono = { version = "0.4", features = ["serde"] }
magic-crypt = { version = "4", default-features = false }
actix-web = "4"
async-lock = "3"
deadpool = "0.10"
deadpool-postgres = "0.12"
scc = "2"
once_cell = "1"
libsqlite3-sys = "0.28.0"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-uuid-1"] }
bytes = "1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }

[workspace.dependencies.rusqlite]
version = "0.31"
features = [
    # We are using the bundled version of rusqlite, so we do not need sqlitelib, headers as a
    # dependency. By default, if we do not bundle, our binary will link against system
    # provided sqlite, which would have been a good thing, if we used system sqlite, our
    # binary size would be smaller, compile time lesser, but unfortunately we can not assume
    # sqlite dynamic library is installed on everyone's machine. We can choose to give two
    # binaries, one with bundled, one without, but it is not worth the tradeoff right now.
    "bundled",
    "column_decltype",
]
