[package]
name = "fastn-ds"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
ftd.workspace = true
actix-web.workspace = true
fastn-migration.workspace = true
deadpool-postgres.workspace = true
deadpool.workspace = true
actix-http.workspace = true
async-lock.workspace = true
http.workspace = true
bytes.workspace = true
camino.workspace = true
chrono.workspace = true
futures-util.workspace = true
magic-crypt.workspace = true
async-trait.workspace = true
tokio-postgres.workspace = true
ignore.workspace = true
rand.workspace = true
dirs.workspace = true
tracing.workspace = true
rusqlite.workspace = true
reqwest.workspace = true
once_cell.workspace = true
url.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
dashmap.workspace = true
wasmtime.workspace = true
ft-sys-shared.workspace = true
