[package]
name = "fastn-ds"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
ftd.workspace = true
actix-web.workspace = true
camino.workspace = true
ignore.workspace = true
dirs.workspace = true
