[package]
name = "fastn-core"
version = "0.1.0"
authors = [
    "Abrar Khan <abrark@fifthtry.com>",
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
]
edition = "2021"
description = "fastn: FTD Package Manager"
license = "MIT"
repository = "https://github.com/fastn-stack/fastn"
homepage = "https://fastn.io"

[features]
default = ["auth"]
# fastn comes with some feature to integrate with fastn controller. fastn controller is a
# separate software, optional. fastn controller is responsible for creating a new fastn
# package, and deploying it on some server, backing content up and so on. fastn has to
# speak with fastn controller, when fastn is managed by fastn controller. Enabling the
# "controller" feature enables that communication.
controller = ["remote"]

# fastn runs in local mode (to be used on your local laptop, or single use server), and in
# remote mode (to be used as a shared server for your entire team). The default is
# local mode.
#
# In local mode the editor acts like a local file editor, any changes done directly
# update the file. In remote mode, only sync can be called, and no direct edits are
# allowed. In future we will also have workspace mode, in which in remote a workspace
# is created for every user, and local edits in the workspace is allowed.
remote = []

auth = ["github-auth"]
github-auth = ["dep:oauth2"]

[dependencies]
# Please do not specify a dependency more precisely than needed. If version "1" works, do
# not specify "1.1.42". This reduces the number of total dependencies, as if you specify
# 1.1.42 and someone else who only needed "1" also specified 1.1.37, we end up having same
# dependency compiled twice.
#
# In future we may discover that our code does not indeed work with "1", say it ony works
# for 1.1 onwards, or 1.1.25 onwards, in which case use >= 1.1.25 etc. Saying our code
# only works for 1.1.42 and not 1.1.41 nor 1.1.43 is really weird, and most likely wrong.
#
# If you are not using the latest version intentionally, please do not list it in this section
# and create it's own [dependencies.<name>] section, and document it with why are you not
# using the latest dependency, and what is the plan.

# ariadne = "0.14"
actix-web = "4"
antidote = "1"
async-lock = "2"
async-recursion = "1"
camino = "1"
clap = "4"
colored = "2"
diffy = "0.3"
edit = "0.1"
env_logger = "0.10"
fastn-package = { path = "../fastn-package" }
fluent = "0.16"
format_num = "0.1"
ftd = { path = "../ftd" }
futures = "0.3"
hyper = "0.14"
ignore = "0.4"
indoc = "2"
intl-memoizer = "0.5"
itertools = "0.10"
magic-crypt = { version = "3", default-features = false }
mime_guess = "2"
oauth2 = { version = "4", optional = true }
once_cell = "1"
realm-lang = "0.1"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
rusqlite = "0.29.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
slug = "0.1"
thiserror = "1"
tokio = { version = "1.27.0", features = ["full"] }
tracing-forest = "0.1"
tracing-subscriber = "0.3"
tracing = "0.1"
url = "2"
zip = "0.6"

#wit-bindgen-host-wasmtime-rust = { git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "45604f58336afaa23a79ed619ef50b69de473688" }
#fastn-utils = { git = "https://github.com/ftd-lang/fastn-utils", rev = "0ce396db408b413f5a4eb6b2c5b87db3829cf879" }
# fastn-utils = { path = "../fastn-utils/crates/fastn-utils-host"}



[dev-dependencies]
indoc = "2"
pretty_assertions = "1"
rusty-hook = "^0.11.2"
fbt-lib = { git = "https://github.com/FifthTry/fbt", rev = "ea0ee98" }
