[package]
name = "fastn-continuation"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
async_provider = ["async-trait"]

[dependencies]
async-trait = { workspace = true, optional = true }
tracing.workspace = true
