name: Cue Checks

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  everything:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Run cargo test
        id: test
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: build --release
      - name: Git clone fastn
        run: bash .github/cue.sh
