name: Integration Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    if: false  # temporarily skipping this test (for debugging other tests)
    runs-on: ubuntu-latest

    env:
      FASTN_DB_URL: postgres://testuser:testpassword@localhost:5432/testdb

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: fastn installation (using source)
        id: fastn-install
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path fastn --profile dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install psycopg2

      - name: Wait for PostgreSQL to start
        run: |
          timeout=30
          until pg_isready -h localhost -p 5432 -U testuser -d testdb || ((timeout-- <= 0)); do
            sleep 1
          done

      - name: Populate sample data
        run: |
          python scripts/populate-table.py

      - name: Test server (port 5000)
        run: |
          python scripts/test-server.py &
          
          # Waiting for the server to start
          sleep 10  # We might want to wait more

      - name: Run integration tests
        run: |
          for folder in integration-tests/*/; do
            (cd "$folder" && fastn test --headless)
          done

  slides-integration-test:
    runs-on: ubuntu-latest

    env:
      FASTN_DB_URL: postgres://admin:admin@localhost:5432/fifthtry
      FASTN_SECRET_KEY: fddfbbb85dcae750433875eb8f0fdced08d72aff

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: fifthtry
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: fastn installation (using source)
        id: fastn-install
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path fastn --profile dev

      - name: Clone Slides repository
        id: clone-slides-repo
        run: |
          git clone https://github.com/FifthTry/slides.git

      - name: Navigate inside slides repository
        id: navigate-inside-slides
        run: |
          cd slides

      - name: Wait for PostgreSQL to start
        run: |
          timeout=30
          until pg_isready -h localhost -p 5432 -U testuser -d testdb || ((timeout-- <= 0)); do
            sleep 1
          done

      - name: Install pip dependencies (sourcing auto.sh)
        id: install-pip-dependencies
        run: |
          source scripts/auto.sh

      - name: Setup django
        id: setup-django
        run: |
          make-migrations
          migrate
          recreate-db

      - name: Start django service
        id: start-django
        run: |
          # This will need secret key
          python backend/manage.py runserver 7999 &
          
          # Waiting for the server to start
          sleep 10  # We might want to wait more

      - name: Run integration tests
        id: slides-integration-tests
        run: |
          cd frontend
          fastn test --headless
