name: Create a new release

on:
  push:
    branches:
      - fix/static_build
jobs:
  release-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        id: build-windows
        continue-on-error: false
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features=auth
      - name: run fastn
        run: ./target/release/fastn.exe --version
