name: Create a new release

on:
  push:
    branches:
      - fix/static_build
jobs:
  # test-release:
  #   name: Build for Linux
  #   runs-on: ubuntu-latest
  #   env:
  #     CARGO_TERM_COLOR: always
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Build-musl
  #       run: |
  #         echo "Building static binaries using ekidd/rust-musl-builder"
  #         docker build -t fastn-build-image -f .github/Dockerfile .
  #         docker run --name fastn-build fastn-build-image
  #         mkdir -p out
  #         docker cp fastn-build:/home/rust/src/target/x86_64-unknown-linux-musl/release/fastn out/
  #     - name: ls files
  #       run: |
  #         ls out/
  #         file out/fastn
  test-release-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        id: build-macos
        continue-on-error: false
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features=auth
      - name: run fastn
        run: ./target/release/fastn --version
