[package]
name = "fastn-router"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
fastn-continuation.workspace = true
fastn-utils.workspace = true
